import './globals.css'
import Web3ContextProvider from '@/context/Web3Context'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Web3ContextProvider>
          {children}
        </Web3ContextProvider>
      </body>
    </html>
  )
}
